const { chromium }=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const {execFileSync}=require('node:child_process');
// Start an authenticated-empty local environment and open its private auth URL in
// agent-browser first. This script uses real UI, RPC, Codex, and Git worktrees.
// Never print the authenticated URL or copy its credentials into this file.
const project=fs.mkdtempSync(path.join(os.tmpdir(),'talos-workflow-setup-'));
fs.writeFileSync(path.join(project,'README.md'),'Workflow setup validation fixture.\n');
execFileSync('git',['init','-q',project]);
execFileSync('git',['-C',project,'add','README.md']);
execFileSync('git',['-C',project,'-c','user.name=Talos Validation','-c','user.email=validation@example.invalid','commit','-qm','Initialize isolated workflow fixture']);
(async()=>{
 const b=await chromium.connectOverCDP(process.env.CDP_URL || 'http://127.0.0.1:9222');
 const p=b.contexts()[0].pages()[0];
 const button=name=>p.getByRole('button',{name,exact:true});
 const evidence=path.resolve('docs/evidence/workflow-setup');
 fs.mkdirSync(evidence,{recursive:true});
 await p.setViewportSize({width:390,height:844});
 if (await button('Cancel setup').count()) await button('Cancel setup').click();
 await button('Create workflow').click();
 await button(process.env.WORKFLOW_MACHINE || os.hostname()).click();
 await button('Use a starter team').waitFor({timeout:30000});
 assert.equal(await button('Use my saved agents').isDisabled(),true);
 await p.getByRole('button',{name:/^Team model:/}).click();
 await button('Use GPT-5.6-Sol').click();
 await p.getByRole('button',{name:/^Reasoning effort:/}).click();
 await button('Use low effort').click();
 await p.screenshot({path:`${evidence}/setup-live-models.png`,fullPage:true});
 await button('Continue to workflow details').click();
 await button('Continue').click();
 await p.getByRole('alert').filter({hasText:'Give this workflow a name'}).waitFor();
 await p.getByRole('textbox',{name:'Workflow name',exact:true}).fill('Starter team delivery');
 await p.getByRole('textbox',{name:'Description',exact:true}).fill('Fresh-account workflow setup validation with real Codex agents.');
 await button('Continue').click();
 await p.getByRole('textbox',{name:'Planner 1 agent name',exact:true}).fill('Aster Setup');
 await button('Edit Planner 1 instructions').click();
 await p.getByRole('textbox',{name:'Planner 1 instructions',exact:true}).fill('Independently plan the requested task. Keep this small fixture task focused. Consolidate proposals preserving any unresolved objections. Verify the acceptance criteria before approving.');
 await button('Hide Planner 1 instructions').click();
 await button('Continue').click();
 await button('Continue').click();
 await p.getByRole('alert').filter({hasText:'Describe what must be true'}).waitFor();
 await p.getByRole('textbox',{name:'Completion criteria',exact:true}).fill('The isolated worktree contains result.txt with exactly talos workflow setup verified followed by a newline. The configured Python check passes. No other source files change.');
 await p.getByRole('textbox',{name:'Check 1 name',exact:true}).fill('Verify result');
 await p.getByRole('textbox',{name:'Check 1 command',exact:true}).fill(`python3 -c 'from pathlib import Path; assert Path("result.txt").read_text() == "talos workflow setup verified\\n"'`);
 await button('Continue').click();
 await p.screenshot({path:`${evidence}/workflow-review.png`,fullPage:true});
 await button('Save workflow').click();
 await p.getByRole('textbox',{name:'Task',exact:true}).waitFor();
 assert.equal(await button('Create workflow').count(),0);
 await button('Start workflow').click();
 await p.getByRole('alert').filter({hasText:'Enter a task'}).waitFor();
 await p.getByRole('textbox',{name:'Task',exact:true}).fill('Create result.txt containing exactly talos workflow setup verified followed by a newline. This is an isolated test fixture. Do not change README.md or any other source files. Run the required verification command. No additional functionality is needed.');
 await p.getByRole('textbox',{name:'Absolute project path',exact:true}).fill(project);
 await p.screenshot({path:`${evidence}/ready-to-start.png`,fullPage:true});
 await button('Start workflow').click();
 await p.waitForURL(/\/workflows\/[0-9a-f-]+\?machineId=/,{timeout:45000});
 const runId=new URL(p.url()).pathname.split('/').at(-1);
 fs.writeFileSync(path.join(os.tmpdir(),`talos-workflow-setup-${runId}.json`),JSON.stringify({runId,url:p.url()}));
 console.log(JSON.stringify({runId,project,started:true,emptyLibrary:true,editedStarter:true,validationErrors:true}));
 await p.screenshot({path:`${evidence}/run-started.png`,fullPage:true});
 await p.getByText('WORKFLOW RUN · COMPLETE',{exact:true}).waitFor({timeout:600000});
 await button('Work').click();
 await p.getByText('Verify result: Passed',{exact:true}).waitFor();
 await p.evaluate(()=>{ for(const el of document.querySelectorAll('*')) if(el.scrollHeight>el.clientHeight) el.scrollTop=0; });
 await p.screenshot({path:`${evidence}/run-complete-mobile.png`});
 assert.equal(fs.existsSync(path.join(project,'result.txt')),false);
 assert.equal(execFileSync('git',['-C',project,'status','--porcelain'],{encoding:'utf8'}),'');
 console.log(JSON.stringify({runId,complete:true,sourceUnchanged:true}));
 await b.close();
})().catch(e=>{console.error(e.message);process.exit(1)});
