packages:
  - "packages/talos-app"
  - "packages/talos-agent"
  - "packages/talos-cli"
  - "packages/talos-server"
  - "packages/talos-wire"
  - "packages/talos-app-logs"
  - "packages/talos-desktop"
