upstream talos_frontend {
    least_conn;
    server 89.125.50.58:32001 max_fails=2 fail_timeout=20s weight=3;
    server 89.125.255.36:32001 max_fails=2 fail_timeout=20s weight=2;
    keepalive 32;
}
upstream talos_api {
    least_conn;
    server 89.125.50.58:32002 max_fails=2 fail_timeout=20s weight=3;
    server 89.125.255.36:32002 max_fails=2 fail_timeout=20s weight=2;
    keepalive 32;
}
upstream talos_files {
    least_conn;
    server 89.125.50.58:30903 max_fails=2 fail_timeout=20s weight=3;
    server 89.125.255.36:30903 max_fails=2 fail_timeout=20s weight=2;
    keepalive 32;
}
map $http_origin $talos_files_origin {
    default "";
    "https://talosapp.ai" "https://talosapp.ai";
}
