# Render with the new Talos cluster nodes and allocated service ports.
upstream talos_api {
    least_conn;
    server ${TALOS_NODE_HOST_1}:${TALOS_API_NODE_PORT} max_fails=2 fail_timeout=20s;
    server ${TALOS_NODE_HOST_2}:${TALOS_API_NODE_PORT} max_fails=2 fail_timeout=20s;
    keepalive 32;
}

upstream talos_files {
    least_conn;
    server ${TALOS_NODE_HOST_1}:${TALOS_FILES_NODE_PORT} max_fails=2 fail_timeout=20s;
    server ${TALOS_NODE_HOST_2}:${TALOS_FILES_NODE_PORT} max_fails=2 fail_timeout=20s;
    keepalive 32;
}
