# Render with the new Talos cluster nodes and allocated service port.
upstream talos_frontend {
    least_conn;
    server ${TALOS_NODE_HOST_1}:${TALOS_WEB_NODE_PORT} max_fails=2 fail_timeout=20s;
    server ${TALOS_NODE_HOST_2}:${TALOS_WEB_NODE_PORT} max_fails=2 fail_timeout=20s;
    keepalive 32;
}
